<?php

use Illuminate\Database\Seeder;
use App\Pais;

class CreatePaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pais = Pais::create(['pais' => '','estado' => true]);
        $pais = Pais::create(['pais' => 'Afganistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Albania','estado' => true]);
        $pais = Pais::create(['pais' => 'Alemania','estado' => true]);
        $pais = Pais::create(['pais' => 'Andorra','estado' => true]);
        $pais = Pais::create(['pais' => 'Angola','estado' => true]);
        $pais = Pais::create(['pais' => 'Antigua y Barbuda','estado' => true]);
        $pais = Pais::create(['pais' => 'Arabia Saudita','estado' => true]);
        $pais = Pais::create(['pais' => 'Argelia','estado' => true]);
        $pais = Pais::create(['pais' => 'Argentina','estado' => true]);
        $pais = Pais::create(['pais' => 'Armenia','estado' => true]);
        $pais = Pais::create(['pais' => 'Australia','estado' => true]);
        $pais = Pais::create(['pais' => 'Austria','estado' => true]);
        $pais = Pais::create(['pais' => 'Azerbaiyán','estado' => true]);
        $pais = Pais::create(['pais' => 'Bahamas','estado' => true]);
        $pais = Pais::create(['pais' => 'Bangladés','estado' => true]);
        $pais = Pais::create(['pais' => 'Barbados','estado' => true]);
        $pais = Pais::create(['pais' => 'Baréin','estado' => true]);
        $pais = Pais::create(['pais' => 'Bélgica','estado' => true]);
        $pais = Pais::create(['pais' => 'Belice','estado' => true]);
        $pais = Pais::create(['pais' => 'Benín','estado' => true]);
        $pais = Pais::create(['pais' => 'Bielorrusia','estado' => true]);
        $pais = Pais::create(['pais' => 'Birmania','estado' => true]);
        $pais = Pais::create(['pais' => 'Bolivia','estado' => true]);
        $pais = Pais::create(['pais' => 'Bosnia y Herzegovina','estado' => true]);
        $pais = Pais::create(['pais' => 'Botsuana','estado' => true]);
        $pais = Pais::create(['pais' => 'Brasil','estado' => true]);
        $pais = Pais::create(['pais' => 'Brunéi','estado' => true]);
        $pais = Pais::create(['pais' => 'Bulgaria','estado' => true]);
        $pais = Pais::create(['pais' => 'Burkina Faso','estado' => true]);
        $pais = Pais::create(['pais' => 'Burundi','estado' => true]);
        $pais = Pais::create(['pais' => 'Bután','estado' => true]);
        $pais = Pais::create(['pais' => 'Cabo Verde','estado' => true]);
        $pais = Pais::create(['pais' => 'Camboya','estado' => true]);
        $pais = Pais::create(['pais' => 'Camerún','estado' => true]);
        $pais = Pais::create(['pais' => 'Canadá','estado' => true]);
        $pais = Pais::create(['pais' => 'Catar','estado' => true]);
        $pais = Pais::create(['pais' => 'Chad','estado' => true]);
        $pais = Pais::create(['pais' => 'Chile','estado' => true]);
        $pais = Pais::create(['pais' => 'China','estado' => true]);
        $pais = Pais::create(['pais' => 'Chipre','estado' => true]);
        $pais = Pais::create(['pais' => 'Ciudad del Vaticano','estado' => true]);
        $pais = Pais::create(['pais' => 'Colombia','estado' => true]);
        $pais = Pais::create(['pais' => 'Comoras','estado' => true]);
        $pais = Pais::create(['pais' => 'Corea del Norte','estado' => true]);
        $pais = Pais::create(['pais' => 'Corea del Sur','estado' => true]);
        $pais = Pais::create(['pais' => 'Costa de Marfil','estado' => true]);
        $pais = Pais::create(['pais' => 'Costa Rica','estado' => true]);
        $pais = Pais::create(['pais' => 'Croacia','estado' => true]);
        $pais = Pais::create(['pais' => 'Cuba','estado' => true]);
        $pais = Pais::create(['pais' => 'Dinamarca','estado' => true]);
        $pais = Pais::create(['pais' => 'Dominica','estado' => true]);
        $pais = Pais::create(['pais' => 'Ecuador','estado' => true]);
        $pais = Pais::create(['pais' => 'Egipto','estado' => true]);
        $pais = Pais::create(['pais' => 'El Salvador','estado' => true]);
        $pais = Pais::create(['pais' => 'Emiratos Árabes Unidos','estado' => true]);
        $pais = Pais::create(['pais' => 'Eritrea','estado' => true]);
        $pais = Pais::create(['pais' => 'Eslovaquia','estado' => true]);
        $pais = Pais::create(['pais' => 'Eslovenia','estado' => true]);
        $pais = Pais::create(['pais' => 'España','estado' => true]);
        $pais = Pais::create(['pais' => 'Estados Unidos','estado' => true]);
        $pais = Pais::create(['pais' => 'Estonia','estado' => true]);
        $pais = Pais::create(['pais' => 'Etiopía','estado' => true]);
        $pais = Pais::create(['pais' => 'Filipinas','estado' => true]);
        $pais = Pais::create(['pais' => 'Finlandia','estado' => true]);
        $pais = Pais::create(['pais' => 'Fiyi','estado' => true]);
        $pais = Pais::create(['pais' => 'Francia','estado' => true]);
        $pais = Pais::create(['pais' => 'Gabón','estado' => true]);
        $pais = Pais::create(['pais' => 'Gambia','estado' => true]);
        $pais = Pais::create(['pais' => 'Georgia','estado' => true]);
        $pais = Pais::create(['pais' => 'Ghana','estado' => true]);
        $pais = Pais::create(['pais' => 'Granada','estado' => true]);
        $pais = Pais::create(['pais' => 'Grecia','estado' => true]);
        $pais = Pais::create(['pais' => 'Guatemala','estado' => true]);
        $pais = Pais::create(['pais' => 'Guyana','estado' => true]);
        $pais = Pais::create(['pais' => 'Guinea','estado' => true]);
        $pais = Pais::create(['pais' => 'Guinea ecuatorial','estado' => true]);
        $pais = Pais::create(['pais' => 'Guinea-Bisáu','estado' => true]);
        $pais = Pais::create(['pais' => 'Haití','estado' => true]);
        $pais = Pais::create(['pais' => 'Honduras','estado' => true]);
        $pais = Pais::create(['pais' => 'Hungría','estado' => true]);
        $pais = Pais::create(['pais' => 'India','estado' => true]);
        $pais = Pais::create(['pais' => 'Indonesia','estado' => true]);
        $pais = Pais::create(['pais' => 'Irak','estado' => true]);
        $pais = Pais::create(['pais' => 'Irán','estado' => true]);
        $pais = Pais::create(['pais' => 'Irlanda','estado' => true]);
        $pais = Pais::create(['pais' => 'Islandia','estado' => true]);
        $pais = Pais::create(['pais' => 'Islas Marshall','estado' => true]);
        $pais = Pais::create(['pais' => 'Islas Salomón','estado' => true]);
        $pais = Pais::create(['pais' => 'Israel','estado' => true]);
        $pais = Pais::create(['pais' => 'Italia','estado' => true]);
        $pais = Pais::create(['pais' => 'Jamaica','estado' => true]);
        $pais = Pais::create(['pais' => 'Japón','estado' => true]);
        $pais = Pais::create(['pais' => 'Jordania','estado' => true]);
        $pais = Pais::create(['pais' => 'Kazajistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Kenia','estado' => true]);
        $pais = Pais::create(['pais' => 'Kirguistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Kiribati','estado' => true]);
        $pais = Pais::create(['pais' => 'Kuwait','estado' => true]);
        $pais = Pais::create(['pais' => 'Laos','estado' => true]);
        $pais = Pais::create(['pais' => 'Lesoto','estado' => true]);
        $pais = Pais::create(['pais' => 'Letonia','estado' => true]);
        $pais = Pais::create(['pais' => 'Líbano','estado' => true]);
        $pais = Pais::create(['pais' => 'Liberia','estado' => true]);
        $pais = Pais::create(['pais' => 'Libia','estado' => true]);
        $pais = Pais::create(['pais' => 'Liechtenstein','estado' => true]);
        $pais = Pais::create(['pais' => 'Lituania','estado' => true]);
        $pais = Pais::create(['pais' => 'Luxemburgo','estado' => true]);
        $pais = Pais::create(['pais' => 'Macedonia del Norte','estado' => true]);
        $pais = Pais::create(['pais' => 'Madagascar','estado' => true]);
        $pais = Pais::create(['pais' => 'Malasia','estado' => true]);
        $pais = Pais::create(['pais' => 'Malaui','estado' => true]);
        $pais = Pais::create(['pais' => 'Maldivas','estado' => true]);
        $pais = Pais::create(['pais' => 'Malí','estado' => true]);
        $pais = Pais::create(['pais' => 'Malta','estado' => true]);
        $pais = Pais::create(['pais' => 'Marruecos','estado' => true]);
        $pais = Pais::create(['pais' => 'Mauricio','estado' => true]);
        $pais = Pais::create(['pais' => 'Mauritania','estado' => true]);
        $pais = Pais::create(['pais' => 'México','estado' => true]);
        $pais = Pais::create(['pais' => 'Micronesia','estado' => true]);
        $pais = Pais::create(['pais' => 'Moldavia','estado' => true]);
        $pais = Pais::create(['pais' => 'Mónaco','estado' => true]);
        $pais = Pais::create(['pais' => 'Mongolia','estado' => true]);
        $pais = Pais::create(['pais' => 'Montenegro','estado' => true]);
        $pais = Pais::create(['pais' => 'Mozambique','estado' => true]);
        $pais = Pais::create(['pais' => 'Namibia','estado' => true]);
        $pais = Pais::create(['pais' => 'Nauru','estado' => true]);
        $pais = Pais::create(['pais' => 'Nepal','estado' => true]);
        $pais = Pais::create(['pais' => 'Nicaragua','estado' => true]);
        $pais = Pais::create(['pais' => 'Níger','estado' => true]);
        $pais = Pais::create(['pais' => 'Nigeria','estado' => true]);
        $pais = Pais::create(['pais' => 'Noruega','estado' => true]);
        $pais = Pais::create(['pais' => 'Nueva Zelanda','estado' => true]);
        $pais = Pais::create(['pais' => 'Omán','estado' => true]);
        $pais = Pais::create(['pais' => 'Países Bajos','estado' => true]);
        $pais = Pais::create(['pais' => 'Pakistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Palaos','estado' => true]);
        $pais = Pais::create(['pais' => 'Panamá','estado' => true]);
        $pais = Pais::create(['pais' => 'Papúa Nueva Guinea','estado' => true]);
        $pais = Pais::create(['pais' => 'Paraguay','estado' => true]);
        $pais = Pais::create(['pais' => 'Perú','estado' => true]);
        $pais = Pais::create(['pais' => 'Polonia','estado' => true]);
        $pais = Pais::create(['pais' => 'Portugal','estado' => true]);
        $pais = Pais::create(['pais' => 'Reino Unido','estado' => true]);
        $pais = Pais::create(['pais' => 'República Centroafricana','estado' => true]);
        $pais = Pais::create(['pais' => 'República Checa','estado' => true]);
        $pais = Pais::create(['pais' => 'República del Congo','estado' => true]);
        $pais = Pais::create(['pais' => 'República Democrática del Congo','estado' => true]);
        $pais = Pais::create(['pais' => 'República Dominicana','estado' => true]);
        $pais = Pais::create(['pais' => 'Ruanda','estado' => true]);
        $pais = Pais::create(['pais' => 'Rumanía','estado' => true]);
        $pais = Pais::create(['pais' => 'Rusia','estado' => true]);
        $pais = Pais::create(['pais' => 'Samoa','estado' => true]);
        $pais = Pais::create(['pais' => 'San Cristóbal y Nieves','estado' => true]);
        $pais = Pais::create(['pais' => 'San Marino','estado' => true]);
        $pais = Pais::create(['pais' => 'San Vicente y las Granadinas','estado' => true]);
        $pais = Pais::create(['pais' => 'Santa Lucía','estado' => true]);
        $pais = Pais::create(['pais' => 'Santo Tomé y Príncipe','estado' => true]);
        $pais = Pais::create(['pais' => 'Senegal','estado' => true]);
        $pais = Pais::create(['pais' => 'Serbia','estado' => true]);
        $pais = Pais::create(['pais' => 'Seychelles','estado' => true]);
        $pais = Pais::create(['pais' => 'Sierra Leona','estado' => true]);
        $pais = Pais::create(['pais' => 'Singapur','estado' => true]);
        $pais = Pais::create(['pais' => 'Siria','estado' => true]);
        $pais = Pais::create(['pais' => 'Somalia','estado' => true]);
        $pais = Pais::create(['pais' => 'Sri Lanka','estado' => true]);
        $pais = Pais::create(['pais' => 'Suazilandia','estado' => true]);
        $pais = Pais::create(['pais' => 'Sudáfrica','estado' => true]);
        $pais = Pais::create(['pais' => 'Sudán','estado' => true]);
        $pais = Pais::create(['pais' => 'Sudán del Sur','estado' => true]);
        $pais = Pais::create(['pais' => 'Suecia','estado' => true]);
        $pais = Pais::create(['pais' => 'Suiza','estado' => true]);
        $pais = Pais::create(['pais' => 'Surinam','estado' => true]);
        $pais = Pais::create(['pais' => 'Tailandia','estado' => true]);
        $pais = Pais::create(['pais' => 'Tanzania','estado' => true]);
        $pais = Pais::create(['pais' => 'Tayikistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Timor Oriental','estado' => true]);
        $pais = Pais::create(['pais' => 'Togo','estado' => true]);
        $pais = Pais::create(['pais' => 'Tonga','estado' => true]);
        $pais = Pais::create(['pais' => 'Trinidad y Tobago','estado' => true]);
        $pais = Pais::create(['pais' => 'Túnez','estado' => true]);
        $pais = Pais::create(['pais' => 'Turkmenistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Turquía','estado' => true]);
        $pais = Pais::create(['pais' => 'Tuvalu','estado' => true]);
        $pais = Pais::create(['pais' => 'Ucrania','estado' => true]);
        $pais = Pais::create(['pais' => 'Uganda','estado' => true]);
        $pais = Pais::create(['pais' => 'Uruguay','estado' => true]);
        $pais = Pais::create(['pais' => 'Uzbekistán','estado' => true]);
        $pais = Pais::create(['pais' => 'Vanuatu','estado' => true]);
        $pais = Pais::create(['pais' => 'Venezuela','estado' => true]);
        $pais = Pais::create(['pais' => 'Vietnam','estado' => true]);
        $pais = Pais::create(['pais' => 'Yemen','estado' => true]);
        $pais = Pais::create(['pais' => 'Yibuti','estado' => true]);
        $pais = Pais::create(['pais' => 'Zambia','estado' => true]);
        $pais = Pais::create(['pais' => 'Zimbabue','estado' => true]);

        
    }
}
